### ISSUE TITLE
[Feature request][iOS 14] Reduced accuracy support in onProviderChange

### ISSUE THREAD

**Issue by Sakarisson** [transistorsoft/react-native-background-geolocation#1116] opened 2020-08-11 18:53 UTC
## Feature request

Hey, sorry for breaking the rule of using the issue template, but I don't think it makes sense for this context.

In iOS 14, which is currently in beta, there will be a new addition to location request prompt. Namely, precision. The user can choose to allow precise updates (which I believe is the default) or toggle them of. As far as I understand, reduced precision only updates approximately 4 times per hour, and is only accurate up to 20 _kilometers_.

As a developer, I would like to know when my users will be using this feature, so I can kindly ask them to turn it off. 

My first thought would be that this could be integrated into `onProviderChange`, but I am not totally sure how the API would look. Do you already have some thoughts on the topic?

Thanks in advance!

Some light reading: https://radar.io/blog/understanding-approximate-location-in-ios-14

**Comment by christocracy** [comment] 2020-08-11 19:41
It'll be implemented this month.

**Comment by Sakarisson** [comment] 2020-08-17 06:05
Thanks for the response! Should I just close this ticket then or wait until the feature is out?

**Comment by christocracy** [comment] 2020-08-17 13:12
You can keep it open for now.  I'll reference this commit once it's pushed.

It's ready now and I'm just documenting it.

**Comment by christocracy** [comment] 2020-08-19 20:46
I've pushed branch `ios14`.  Please try it out with *XCode 12 beta* on iOS 14 device and let me know asap.  Please also try this branch with **XCode 11** on your iOS 13 device (if you have one).

```
$ yarn add https://github.com/transistorsoft/react-native-background-geolocation.git#ios14
```

- [Added][iOS] iOS 14 introduces a new switch on the initial location authorization dialog, allowing the user to "disable precise locadtion".  In support of this, a new method `BackgroundGeolocation.requestTemporaryFullAccuracy` has been added for requesting the user enable "temporary high accuracy" (until the next launch of your app), in addition to a new attribute `ProviderChangeEvent.accuracyAuthorization` for learning its state in the event `onProviderChange`:
![](https://dl.dropbox.com/s/dj93xpg51vspqk0/ios-14-precise-on.png?dl=1)

```javascript
BackgroundGeolocation.onProviderChange((event) => {
  print("[providerchange]", event);
  // Did the user disable precise locadtion in iOS 14+?
  if (event.accuracyAuthorization == BackgroundGeolocation.ACCURACY_AUTHORIZATION_REDUCED) {
    // Supply "Purpose" key from Info.plist as 1st argument.
    BackgroundGeolocation.requestTemporaryFullAccuracy("DemoPurpose").then((accuracyAuthorization) => {
      if (accuracyAuthorization == BackgroundGeolocation.ACCURACY_AUTHORIZATION_FULL) {
        console.log("[requestTemporaryFullAccuracy] GRANTED:", accuracyAuthorization);
      } else {
        console.log("[requestTemporaryFullAccuracy] DENIED:", accuracyAuthorization);
      }
    }).catch((error) => {
      console.log("[requestTemporaryFullAccuracy] FAILED TO SHOW DIALOG:", error);
    });
  }
}
```
These changes are fully compatible with Android, which will always return `BackgroundGeolocation.ACCURACY_AUTHORIZATION_FULL`

- [Added][Android] Add `onChange` listener for `Config.locationAuthorizationRequest` to request location-authorization.
- [Changed][iOS] If `locationAuthorizationRequest == 'WhenInUse'` and the user has granted the higher level of `Always` authorization, do not show `locationAuthorizationAlert`.
- [Changed][iOS] When `locationAuthorizationRequest: 'Always'`, the SDK will now initially request `WhenInUse` followed immediately with another request for `Always`, rather than having to wait an unknown length of time for iOS to show the authorization upgrade dialog:
- [Added][iOS] Apple has changed the behaviour of location authorization &mdash; if an app initially requests `When In Use` location authorization then later requests `Always` authorization, iOS will *immediately* show the authorization upgrade dialog (`[Keep using When in Use`] / `[Change to Always allow]`).

__Example__
```javascript
componentDidMount() {
  BackgroundGeolocation.ready({
    locationAuthorizationRequest: 'WhenInUse',
    .
    .
    .
  });
}

async onClickStartTracking() {
  await BackgroundGeolocation.start();

  //
  // some time later -- could be immediately after, hours later, days later, etc.
  //
  // Simply update `locationAuthorizationRequest` to "Always" -- the SDK will cause iOS to automatically show the authorization upgrade dialog.
  BackgroundGeolocation.setConfig({
    locationAuthorizationRequest: 'Always'
  });
}
```

![](https://dl.dropbox.com/s/0alq10i4pcm2o9q/ios-when-in-use-to-always-CHANGELOG.gif?dl=1)

**Comment by christocracy** [comment] 2020-08-19 20:56
**Note:** To use the new method `BackgroundGeolocation.requestTemporaryFullAccuracy` requires new configuration in `Info.plist`:

## Configuration &mdash; `Info.plist`

In order to use this method, you must configure your __`Info.plist`__ with the `Dictionary` key:
 __`Privacy - Location Temporary Usage Description Dictionary`__

 ![](https://dl.dropbox.com/s/52f5lnjc4d9g8w7/ios-14-Privacy-Location-Temporary-Usage-Description-Dictionary.png?dl=1)

The keys of this `Dictionary` (eg: `Delivery`) are supplied as the first argument to the method.  The `value` will be printed on the dialog shown to the user, explaing the purpose of your request for full accuracy.

If the dialog fails to be presented, an error will be thrown:
 - The Info.plist file doesn’t have an entry for the given purposeKey value.
- The app is already authorized for full accuracy.
- The app is in the background.

 ![](https://dl.dropbox.com/s/8cc0sniv3pvpetl/ios-14-requestTemporaryFullAccuracy.png?dl=1)

**Comment by lfkwtz** [comment] 2020-09-16 17:38
How does non-accurate location affect geofences? I'm guessing it'll be triggering them more often?

**Comment by christocracy** [comment] 2020-09-16 18:31
>How does non-accurate location affect geofences?

I'm not sure.  I haven't actually field-tested with `[Precise: OFF]` yet.  I'll try that.

**Comment by lfkwtz** [comment] 2020-09-16 18:37
> > How does non-accurate location affect geofences?
> 
> I'm not sure. I haven't actually field-tested with `[Precise: OFF]` yet. I'll try that.

I just did some quick testing and from what I'm seeing, the article I shared was correct and it's not triggering any geofences. Which, is probably better than getting bad data.

**Comment by firdaussoberi** [comment] 2020-09-30 04:24
> I've pushed branch `ios14`. Please try it out with _XCode 12 beta_ on iOS 14 device and let me know asap. Please also try this branch with **XCode 11** on your iOS 13 device (if you have one).
>

Hi @christocracy just to be sure, this has been pushed to v3.9.0 right? Also trying it now.

**Comment by christocracy** [comment] 2020-09-30 04:25
See the readme.

**Comment by christocracy** [comment] 2020-09-30 04:26
CHANGELOG, rather

**Comment by firdaussoberi** [comment] 2020-09-30 05:30
> > I've pushed branch `ios14`. Please try it out with _XCode 12 beta_ on iOS 14 device and let me know asap. Please also try this branch with **XCode 11** on your iOS 13 device (if you have one).
> 
> Hi @christocracy just to be sure, this has been pushed to v3.9.0 right? Also trying it now.

Thanks. It works on my end now, on iOS14 I see log events each ~30sec. requestTemporaryFullAccuracy works as intended with the double prompt.

**Comment by raymatos** [comment] 2020-10-07 15:35
when will this be merged?

**Comment by christocracy** [comment] 2020-10-07 15:37
@raymatos Why do you think it hasn't been merged?  Have you seen the [CHANGELOG](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/CHANGELOG.md#390--2020-08-20)

**Comment by raymatos** [comment] 2020-10-07 15:38
@christocracy Issue was still open, so i assumed it was not merged.  Silly me :)

**Closed** 2020-10-07 15:39 UTC
Labels: enhancement, iOS
