### ISSUE TITLE
react-native link commands broken

### ISSUE THREAD

**Issue by ryanostrom** [transistorsoft/react-native-background-geolocation#438] opened 2018-03-17 16:07 UTC
## Summary

**Given** I have followed the instructions for installing the app with react-native link
**Then** I expect the project to link successfully and build successfully
**Instead**, when I run the link commands for `react-native-background-geolocation` and `react-native-background-fetch` I receive the following error:

```
fs.js:653
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/user/sites/project/app/ios/app.xcodeproj/project.pbxproj'
```
**And** when I run `npm run ios` I receive the following error TSBackgroundFetch.framework not found

I was able to resolve the issue by walking through the manual setup process. The linking commands had correctly done the first half of the manual instructions, but it failed to add the TS frameworks to link with libraries, and also failed to add the framework search paths for those libraries.

## Environment
* Plugin version: 2.11.0
* Platform: iOS
* OS version: 11.*
* Device manufacturer / model: Simulator
* React Native version: 0.49.5

## Steps to Reproduce
1. Start a new react-native project
2. Follow the instructions to react-native link the three libraries
3. Follow the rest of the instructions as per the documentation
4. Not the two links for react-native-background* fail
5. Run react-native run-ios
6. Note the build fails

## Context
Install the library

## Recommendation
Review the install scripts to determine what the issue might be so that others don't experience this same issue.

**Comment by christocracy** [comment] 2018-03-17 16:08
What's your XCode version?

**Comment by ryanostrom** [comment] 2018-03-17 16:23
@christocracy  9.2

**Comment by christocracy** [comment] 2018-03-17 16:26
It looks like react-native has done something to the project structure of the iOS app, breaking my custom scripts.

Use Manual installation instructions for now until I figure out what broke.

**Comment by ryanostrom** [comment] 2018-03-17 16:28
Thanks for the quick response @christocracy -- no rush on this, just wanted to give you a heads up!

**Comment by christocracy** [comment] 2018-03-19 17:46
I believe I've found the cause of this.

**Comment by olegwn** [comment] 2018-03-20 05:49
Same thing here, manual setup worked

**Comment by christocracy** [comment] 2018-03-21 20:33
Published [`2.12.0-beta.1`](https://github.com/transistorsoft/react-native-background-geolocation/issues/442).  This version has changed the Android setup slightly and introduces some API changes.

`react-native link` should be fixed.

**Closed** 2018-03-22 23:16 UTC
Labels: bug

**Comment by tetogomez** [comment] 2018-04-22 00:13
@christocracy I tried with 'react-native link' but I got the same error:
`
return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/macbookproretina/Documents/Adsa/driver-app-v2/ios/driver-app-v2.xcodeproj/project.pbxproj'
`

**Comment by christocracy** [comment] 2018-04-22 00:15
You probably need this PR https://github.com/transistorsoft/react-native-background-geolocation/pull/460

Use manual setup for now.
