### ISSUE TITLE
App Crash On Release Mode

### ISSUE THREAD

**Issue by premadinfotech** [transistorsoft/react-native-background-geolocation#1535] opened 2022-08-30 13:01 UTC
We have integrated your library and it is working fine in debug mode but when we are going to create release build then build is creating successfully but when we install this apk in any phone then it crashes and not working. We are not sure what is the issue. Can you please help us. We are getting stuck in this issues from 5 hours.

## Your Environment
* Plugin version: 3.10.0
* Platform: Android
* OS version: 12
* Device manufacturer / model: Vivo (IQOO Z5)
* React Native version (`react-native -v`): 0.64.1
* Plugin config

**Build.gradle**
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "29.0.3"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 30
        ndkVersion = "20.1.5948944"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:4.1.0")
        classpath 'com.google.gms:google-services:4.3.8'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }
         maven {
           // Required for react-native-background-geolocation
           url("${project(':react-native-background-geolocation').projectDir}/libs")
       }
       maven {
           // Required for react-native-background-fetch
           url("${project(':react-native-background-fetch').projectDir}/libs")
       }
    }
}
```

**Android/App/Build.gradle**
```
apply plugin: "com.android.application"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation. If none specified and
 *   // "index.android.js" exists, it will be used. Otherwise "index.js" is
 *   // default. Can be overridden with ENTRY_FILE environment variable.
 *   entryFile: "index.android.js",
 *
 *   // https://reactnative.dev/docs/performance#enable-the-ram-format
 *   bundleCommand: "ram-bundle",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/*", "ios/*"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    enableHermes: false,  // clean and rebuild if changing
]

apply from: "../../node_modules/react-native/react.gradle"

Project background_geolocation = project(':react-native-background-geolocation')
apply from: "${background_geolocation.projectDir}/app.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

/**
 * The preferred build flavor of JavaScriptCore.
 *
 * For example, to use the international variant, you can use:
 * `def jscFlavor = 'org.webkit:android-jsc-intl:+'`
 *
 * The international variant includes ICU i18n library and necessary data
 * allowing to use e.g. `Date.toLocaleString` and `String.localeCompare` that
 * give correct results when using with locales other than en-US.  Note that
 * this variant is about 6MiB larger per architecture than default.
 */
def jscFlavor = 'org.webkit:android-jsc:+'

/**
 * Whether to enable the Hermes VM.
 *
 * This should be set on project.ext.react and mirrored here.  If it is not set
 * on project.ext.react, JavaScript will not be compiled to Hermes Bytecode
 * and the benefits of using Hermes will therefore be sharply reduced.
 */
def enableHermes = project.ext.react.get("enableHermes", false);

android {
    ndkVersion rootProject.ext.ndkVersion

    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.aapnitaxidriver"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 18
        versionName "1.0.2"
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }

        release {
            if (project.hasProperty('MYAPP_UPLOAD_STORE_FILE')) {
                storeFile file(MYAPP_UPLOAD_STORE_FILE)
                storePassword MYAPP_UPLOAD_STORE_PASSWORD
                keyAlias MYAPP_UPLOAD_KEY_ALIAS
                keyPassword MYAPP_UPLOAD_KEY_PASSWORD
            }
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug
            signingConfig signingConfigs.release
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }

    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.html
            // Example: versionCode 1 will generate 1001 for armeabi-v7a, 1002 for x86, etc.
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        defaultConfig.versionCode * 1000 + versionCodes.get(abi)
            }

        }
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    //noinspection GradleDynamicVersion
    implementation "com.facebook.react:react-native:+"  // From node_modules


    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"

    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
      exclude group:'com.facebook.fbjni'
    }

    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
        exclude group:'com.squareup.okhttp3', module:'okhttp'
    }

    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }

    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
apply plugin: 'com.google.gms.google-services'
```

## Expected Behavior
Should not crash on release mode

## Actual Behavior
Crashes on release mode

**Comment by christocracy** [comment] 2022-08-30 13:15
>then it crashes and not working

Why not provide the stacktrace from `$ adb logcat`?

>Plugin version: 3.10.0

Why do you insist upon using an *old* version of the plugin instead of latest `4.8.1`?

**Comment by premadinfotech** [comment] 2022-08-30 13:18
But Chris 1533 issue was marked as closed by you and at that time we got stuck in creating the build but now we are able to create the build but our apk is crashing after installing. 

we tried with the latest version but we were getting the same error (app crashes after installation) and also getting crash issue in debug mode. so we downgrade plugin version.

And how can I share adb logcat if the app is crashing after installation? Please suggest.

**Comment by christocracy** [comment] 2022-08-30 13:28
You build *locally* a *release* version and observe `$ adb logcat` for the stacktrace.

**Comment by christocracy** [comment] 2022-08-30 13:29
When you have a crash, the **FIRST** thing you do is get the *stacktrace*.  You don't ignore it and start reaching for a different version.

**Comment by christocracy** [comment] 2022-08-30 13:31
```gradle
allprojects {
    repositories {
        .
        .
        .
        jcenter()
```

You you know that [jcenter is deprecated](https://blog.gradle.org/jcenter-shutdown)?  You're supposed to replace with `mavenCentral()`

**Comment by christocracy** [comment] 2022-08-30 13:34
`compileSdkVersion = 29`

The latest version of the plugin requires `compilesSdkVersion 31`.   It's perfectly fine for `compileSdkVersion` to be *higher than* `targetSdkVersion`.

**Comment by premadinfotech** [comment] 2022-08-30 13:46
Attaching stacktrace file.

[release_build_stacktrace.txt](https://github.com/transistorsoft/react-native-background-geolocation/files/9453350/release_build_stacktrace.txt)

**Comment by christocracy** [comment] 2022-08-30 13:46
>BUILD SUCCESSFUL in 3m 45s

That is *not* a stacktrace.

You said "*but when we install this apk in any phone then it crashes and not working*".

When an app crashes, the OS prints the stacktrace to `logcat`.

**Comment by christocracy** [comment] 2022-08-30 13:48
> Unable to upgrade it. So using old version.

Are you not interested in supporting *Android 12*?

**Comment by premadinfotech** [comment] 2022-08-30 13:49
I am so sorry but how can we get the stacktrace when the app build is "RELEASE" and also we have not published this app on play store still. So how can we get it?

**Comment by christocracy** [comment] 2022-08-30 13:50
While observing `$ adb logcat` in a terminal window, run:

```
$ npx react-native run-android --variant=release
```

**Comment by premadinfotech** [comment] 2022-08-30 13:50
> > Unable to upgrade it. So using old version.
> 
> Are you not interested in supporting _Android 12_?

But we are getting the crash issue on Android 11 also.

**Comment by christocracy** [comment] 2022-08-30 13:51
Answer the question:  *"Are you not interested in supporting Android 12?"*

**Comment by premadinfotech** [comment] 2022-08-30 13:52
> Answer the question: _"Are you not interested in supporting Android 12?"_: Yes or no.

Yes we have to support Android 12 also.

**Comment by christocracy** [comment] 2022-08-30 13:53
v3.10.0 does not support *Android 12*.  Android 12 support first arrived in v4.  You must use the latest version `4.8.1` to properly support Android 12.

**Comment by premadinfotech** [comment] 2022-08-30 13:59
`Launching lib\main.dart on CPH2001 in debug mode...
Running Gradle task 'assembleDebug'...
E/AndroidRuntime(21617): FATAL EXCEPTION: main
E/AndroidRuntime(21617): Process: com.aapnitaxidriver, PID: 21617
E/AndroidRuntime(21617): java.lang.RuntimeException: Unable to create application com.aapnitaxidriver.MainApplication: java.lang.SecurityException: uid 10819 does not have android.permission.ACCESS_COARSE_LOCATION or android.permission.ACCESS_FINE_LOCATION.
E/AndroidRuntime(21617): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7299)
E/AndroidRuntime(21617): 	at android.app.ActivityThread.access$1700(ActivityThread.java:299)
E/AndroidRuntime(21617): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2184)
E/AndroidRuntime(21617): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(21617): 	at android.os.Looper.loop(Looper.java:264)
E/AndroidRuntime(21617): 	at android.app.ActivityThread.main(ActivityThread.java:8312)
E/AndroidRuntime(21617): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21617): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
E/AndroidRuntime(21617): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
E/AndroidRuntime(21617): Caused by: java.lang.SecurityException: uid 10819 does not have android.permission.ACCESS_COARSE_LOCATION or android.permission.ACCESS_FINE_LOCATION.
E/AndroidRuntime(21617): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2389)
E/AndroidRuntime(21617): 	at android.os.Parcel.createException(Parcel.java:2373)
E/AndroidRuntime(21617): 	at android.os.Parcel.readException(Parcel.java:2356)
E/AndroidRuntime(21617): 	at android.os.Parcel.readException(Parcel.java:2298)
E/AndroidRuntime(21617): 	at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:1300)
E/AndroidRuntime(21617): 	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:1193)
E/AndroidRuntime(21617): 	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:1154)
E/AndroidRuntime(21617): 	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:946)
E/AndroidRuntime(21617): 	at com.aapnitaxidriver.MainApplication.onCreate(MainApplication.java:86)
E/AndroidRuntime(21617): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
E/AndroidRuntime(21617): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7294)
E/AndroidRuntime(21617): 	... 8 more
E/AndroidRuntime(21617): Caused by: android.os.RemoteException: Remote stack trace:
E/AndroidRuntime(21617): 	at com.android.server.location.CallerIdentity.enforceLocationPermission(CallerIdentity.java:147)
E/AndroidRuntime(21617): 	at com.android.server.location.CallerIdentity.enforceLocationPermission(CallerIdentity.java:214)
E/AndroidRuntime(21617): 	at com.android.server.location.LocationManagerService.requestLocationUpdates(LocationManagerService.java:2210)
E/AndroidRuntime(21617): 	at com.android.server.location.OplusLocationManagerService.requestLocationUpdates(OplusLocationManagerService.java:327)
E/AndroidRuntime(21617): 	at android.location.ILocationManager$Stub.onTransact(ILocationManager.java:542)
E/AndroidRuntime(21617): 
E/AndroidRuntime(21704): FATAL EXCEPTION: main
E/AndroidRuntime(21704): Process: com.aapnitaxidriver, PID: 21704
E/AndroidRuntime(21704): java.lang.RuntimeException: Unable to create application com.aapnitaxidriver.MainApplication: java.lang.SecurityException: uid 10819 does not have android.permission.ACCESS_COARSE_LOCATION or android.permission.ACCESS_FINE_LOCATION.
E/AndroidRuntime(21704): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7299)
E/AndroidRuntime(21704): 	at android.app.ActivityThread.access$1700(ActivityThread.java:299)
E/AndroidRuntime(21704): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2184)
E/AndroidRuntime(21704): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(21704): 	at android.os.Looper.loop(Looper.java:264)
E/AndroidRuntime(21704): 	at android.app.ActivityThread.main(ActivityThread.java:8312)
E/AndroidRuntime(21704): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21704): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
E/AndroidRuntime(21704): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
E/AndroidRuntime(21704): Caused by: java.lang.SecurityException: uid 10819 does not have android.permission.ACCESS_COARSE_LOCATION or android.permission.ACCESS_FINE_LOCATION.
E/AndroidRuntime(21704): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2389)
E/AndroidRuntime(21704): 	at android.os.Parcel.createException(Parcel.java:2373)
E/AndroidRuntime(21704): 	at android.os.Parcel.readException(Parcel.java:2356)
E/AndroidRuntime(21704): 	at android.os.Parcel.readException(Parcel.java:2298)
E/AndroidRuntime(21704): 	at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:1300)
E/AndroidRuntime(21704): 	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:1193)
E/AndroidRuntime(21704): 	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:1154)
E/AndroidRuntime(21704): 	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:946)
E/AndroidRuntime(21704): 	at com.aapnitaxidriver.MainApplication.onCreate(MainApplication.java:86)
E/AndroidRuntime(21704): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
E/AndroidRuntime(21704): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7294)
E/AndroidRuntime(21704): 	... 8 more
E/AndroidRuntime(21704): Caused by: android.os.RemoteException: Remote stack trace:
E/AndroidRuntime(21704): 	at com.android.server.location.CallerIdentity.enforceLocationPermission(CallerIdentity.java:147)
E/AndroidRuntime(21704): 	at com.android.server.location.CallerIdentity.enforceLocationPermission(CallerIdentity.java:214)
E/AndroidRuntime(21704): 	at com.android.server.location.LocationManagerService.requestLocationUpdates(LocationManagerService.java:2210)
E/AndroidRuntime(21704): 	at com.android.server.location.OplusLocationManagerService.requestLocationUpdates(OplusLocationManagerService.java:327)
E/AndroidRuntime(21704): 	at android.location.ILocationManager$Stub.onTransact(ILocationManager.java:542)
E/AndroidRuntime(21704): `

**Comment by christocracy** [comment] 2022-08-30 14:03
Your stacktrace does not reference any symbol from this plugin (`com.transistorsoft`).

The plugin has its own `AndroidManifest.xml` which contains all required permissions, including:

```xml
<uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACTIVITY_RECOGNITION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="com.google.android.gms.permission.ACTIVITY_RECOGNITION" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM" />
```

This is not the plugin responsible for that stacktrace.

**Comment by premadinfotech** [comment] 2022-08-30 14:09
You mean that these permissions we do not need to define in our manifest.xml and I can remove it from my manifest.xml 
Am I correct ?

**Comment by christocracy** [comment] 2022-08-30 14:16
The plugin's `AndroidManifest` is *merged* with your app's `AndroidManifest`.  

Your app **does not need to** explicitly define *any* of the above permissions.

**Comment by premadinfotech** [comment] 2022-08-30 14:30
Actually, what is happening in android 11, after the installation of the app if we provide location permission manually then we are able to open the app. But in realtime user will not go and provide the manual permission. How can we handle it?

**Comment by christocracy** [comment] 2022-08-30 14:34
The plugin contains all the code necessary for requesting permission from the user when the `.start()` method is called.

**Comment by premadinfotech** [comment] 2022-08-30 14:38
Logcats:

[now.txt](https://github.com/transistorsoft/react-native-background-geolocation/files/9453775/now.txt)

**Comment by christocracy** [comment] 2022-08-30 14:45
The plugin itself clearly has permission `ACCESS_FINE_LOCATION` permission.  It received a location:
```
08-30 19:45:56.190 17270 18073 I TSLocationManager: ╔═════════════════════════════════════════════
08-30 19:45:56.190 17270 18073 I TSLocationManager: ║ motionchange LocationResult: 1
08-30 19:45:56.190 17270 18073 I TSLocationManager: ╠═════════════════════════════════════════════
08-30 19:45:56.190 17270 18073 I TSLocationManager: ╟─ 📍  Location[fused *** hAcc=20.571 et=+10d19h25m19s189ms alt=316.1999816894531 vAcc=1.2054763 vel=0.017824313 bear=168.61667 {Bundle[EMPTY_PARCEL]}], age: 36ms, time: 1661868956153
.
.
.
08-30 19:46:23.523 17270 18074 I TSLocationManager: [c.t.l.s.LocationRequestService b]
08-30 19:46:23.523 17270 18074 I TSLocationManager: ╔═════════════════════════════════════════════
08-30 19:46:23.523 17270 18074 I TSLocationManager: ║ getCurrentPosition LocationResult: 3
08-30 19:46:23.523 17270 18074 I TSLocationManager: ╠═════════════════════════════════════════════
08-30 19:46:23.523 17270 18074 I TSLocationManager: ╟─ 📍  Location[fused *** hAcc=18.51 et=+10d19h25m46s527ms alt=316.1999816894531 vAcc=1.0442122 vel=0.12832816 bear=151.11029 {Bundle[EMPTY_PARCEL]}], age: 32ms, time: 1661868984000

```

Do you have a question about that latest `logcat`?

**Comment by premadinfotech** [comment] 2022-08-30 15:07
Please find the latest updated logcat. 

Only issue is when we install the application then aap is not starting due to the location permission. And we have mentioned .start() function in index.js but still our app is crashing.

Kindly suggest us.
[now (1).txt](https://github.com/transistorsoft/react-native-background-geolocation/files/9454049/now.1.txt)

**Comment by christocracy** [comment] 2022-08-30 15:11
I really have no idea.  Your crash is not caused by the plugin.  If it were, there would be `com.transistorsoft` references in the stacktrace.

clearly you’re dealing with some old code, struggling to build an app while not upgrading old dependencies.

I suggest you attempt to reproduce this issue in a simple Hello World app.

**Comment by premadinfotech** [comment] 2022-08-30 16:25
Does your plugin need a headless service to access the location in background?

**Comment by christocracy** [comment] 2022-08-30 16:33
>Does your plugin need a headless service to access the location in background?

No.  a custom *Headless callback* is *optional*, required only if you have custom javascript business logic to execute while your app is terminated.

The plugin is perfectly capable of operating without a custom headless callback.

**Comment by premadinfotech** [comment] 2022-08-30 18:14
Can you please let me know how many APIs hit if our application move in a car? I want to know this because the API is hit so constantly and all our resources on the server are exhausted. API is hitting like 3000 times in just 1 KM.

**Comment by christocracy** [comment] 2022-08-30 18:16
This issue is titled “* App Crash On Release Mode*”.

is your issue solved?

if you have unrelated questions, post a new issue.

**Comment by premadinfotech** [comment] 2022-08-30 18:18
Sorry for asking this in the same. Yes the issue is closed. Thanks for your help. I will raise a new issue regarding my next concern.

**Closed** 2022-08-30 18:18 UTC
