### ISSUE TITLE
Activity recognition Android 12 Samsung

### ISSUE THREAD

**Issue by shablenko-sednor** [transistorsoft/react-native-background-geolocation#1462] opened 2022-03-24 17:00 UTC
## Your Environment
* Plugin version: 4.4.2
* Platform: Android
* OS version: 12
* Device manufacturer / model: Samsung S21 
* React Native version (`react-native -v`): 0.64.0
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->

{
      notification: {
        channelName: NotificationChannels.SERVICE,
        title: 'Title',
        text: '',
      },
      locationAuthorizationRequest: 'Always',
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      stopOnTerminate: false,
      startOnBoot: true,
    }
```

## Expected Behavior
Should consistently track location\activity changes

## Actual Behavior
Triggers location\activity\motion listeners once after a start, and then never again

## Context
I followed `donotkillmyapp` steps and turned off all battery optimizations
I tried physically moving around, shaking device, tossing it e.t.c.
It worked on Samsung S8 (Android 9), I no longer have access to that device to test

I have seen some posts, that say there are problems with Samsung devices and activity recognition. If it is the case, is there any way to just track location changes without activities in background?

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
03-24 18:26:00.759 DEBUG [LoggerFacade$a a] ℹ️   Persist config, dirty: []
03-24 18:26:00.761 DEBUG [LoggerFacade$a a] ℹ️   Persist config, dirty: [headlessJobService]
03-24 18:38:14.508 INFO [LoggerFacade$a a]
╔═════════════════════════════════════════════
║ TSLocationManager version: 3.1.34 (390)
╠═════════════════════════════════════════════
╟─ samsung SM-G991U1 @ 12 (react-native)
{
"activityRecognitionInterval": 10000,
"allowIdenticalLocations": false,
"authorization": {},
"autoSync": true,
"autoSyncThreshold": 0,
"backgroundPermissionRationale": {
"title": "Allow {applicationName} to access this device's location even when closed or not in use?",
"message": "[CHANGEME] This app collects location data for FEATURE X and FEATURE Y.",
"positiveAction": "Change to \"{backgroundPermissionOptionLabel}\"",
"negativeAction": ""
},
"batchSync": false,
"configUrl": "",
"debug": false,
"deferTime": 0,
"desiredAccuracy": 0,
"desiredOdometerAccuracy": 100,
"disableAutoSyncOnCellular": false,
"disableElasticity": false,
"disableLocationAuthorizationAlert": false,
"disableMotionActivityUpdates": false,
"disableStopDetection": false,
"distanceFilter": 10,
"elasticityMultiplier": 1,
"enableHeadless": false,
"enableTimestampMeta": false,
"extras": {},
"fastestLocationUpdateInterval": -1,
"foregroundService": true,
"geofenceInitialTriggerEntry": true,
"geofenceModeHighAccuracy": false,
"geofenceProximityRadius": 1000,
"geofenceTemplate": "",
"headers": {},
"headlessJobService": "com.transistorsoft.rnbackgroundgeolocation.HeadlessTask",
"heartbeatInterval": -1,
"httpRootProperty": "location",
"httpTimeout": 60000,
"isMoving": false,
"locationAuthorizationRequest": "Always",
"locationTemplate": "",
"locationTimeout": 60,
"locationUpdateInterval": 1000,
"locationsOrderDirection": "ASC",
"logLevel": 0,
"logMaxDays": 3,
"maxBatchSize": -1,
"maxDaysToPersist": 1,
"maxRecordsToPersist": -1,
"method": "POST",
"minimumActivityRecognitionConfidence": 75,
"motionTriggerDelay": 0,
"notification": {
"layout": "",
"title": "",
"text": "Location Service activated",
"color": "",
"channelName": "TSLocationManager",
"smallIcon": "",
"largeIcon": "",
"priority": 0,
"sticky": false,
"strings": {},
"actions": []
},
"params": {},
"persist": true,
"persistMode": 2,
"schedule": [],
"scheduleUseAlarmManager": false,
"speedJumpFilter": 300,
"startOnBoot": false,
"stationaryRadius": 25,
"stopAfterElapsedMinutes": 0,
"stopOnStationary": false,
"stopOnTerminate": true,
"stopTimeout": 5,
"triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
"url": "",
"useSignificantChangesOnly": false,
"enabled": false,
"schedulerEnabled": false,
"trackingMode": 1,
"odometer": 0,
"isFirstBoot": false,
"didLaunchInBackground": false,
"didDeviceReboot": false
}
03-24 18:38:14.516 INFO [LoggerFacade$a a]
╔═════════════════════════════════════════════
║ DEVICE SENSORS
╠═════════════════════════════════════════════
╟─ ✅  ACCELEROMETER: {Sensor name="LSM6DSO Accelerometer", vendor="STMicro", version=15933, type=1, maxRange=78.4532, resolution=0.0023928226, power=0.17, minDelay=2404}
╟─ ✅  GYROSCOPE: {Sensor name="LSM6DSO Gyroscope", vendor="STMicro", version=15933, type=4, maxRange=17.453018, resolution=6.108648E-4, power=0.55, minDelay=2404}
╟─ ✅  MAGNETOMETER: {Sensor name="AK09918 Magnetometer", vendor="akm", version=146966, type=2, maxRange=4912.0503, resolution=0.15, power=1.1, minDelay=10000}
╟─ ✅  SIGNIFICANT_MOTION: {Sensor name="smd  Wakeup", vendor="Samsung", version=1, type=17, maxRange=1.0, resolution=1.0, power=0.001, minDelay=-1}
╚═════════════════════════════════════════════
03-24 18:38:14.517 INFO [LoggerFacade$a a]
✅  Google Play Services: connected (version code:12451000)
03-24 18:38:14.523 INFO [LoggerFacade$a a]
🎾  Start monitoring location-provider changes
03-24 18:38:14.549 DEBUG [a onCreate] CREATE TABLE IF NOT EXISTS locations (id INTEGER PRIMARY KEY AUTOINCREMENT, uuid TEXT NOT NULL DEFAULT '', timestamp TEXT, json TEXT, data BLOB, encrypted BOOLEAN NOT NULL DEFAULT 0, locked BOOLEAN NOT NULL DEFAULT 0);
03-24 18:38:14.549 DEBUG [a onCreate] CREATE TABLE IF NOT EXISTS geofences (id INTEGER PRIMARY KEY AUTOINCREMENT, identifier TEXT NOT NULL UNIQUE, latitude DOUBLE NOT NULL, sin_latitude DOUBLE NOT NULL, cos_latitude DOUBLE NOT NULL, longitude DOUBLE NOT NULL, sin_longitude DOUBLE NOT NULL, cos_longitude DOUBLE NOT NULL, radius DOUBLE NOT NULL, notifyOnEntry BOOLEAN NOT NULL DEFAULT 0, notifyOnExit BOOLEAN NOT NULL DEFAULT 0, notifyOnDwell BOOLEAN NOT NULL DEFAULT 0, loiteringDelay INTEGER NOT NULL DEFAULT 0, extras TEXT);
03-24 18:38:14.560 DEBUG [b prune]
ℹ️  PRUNE -1 days
03-24 18:38:14.678 INFO [BootReceiver$a run]
╔═════════════════════════════════════════════
║ BootReceiver: com.awesomeapp.asdasd
╠═════════════════════════════════════════════
╟─ android.intent.action.MY_PACKAGE_REPLACED

03-24 18:38:14.722 DEBUG [TSGeofenceManager c] ℹ️  Persist monitored geofences: []
03-24 18:38:36.916 DEBUG [TSConfig d] ℹ️   Persist config, dirty: [extras, headers, headlessJobService, params, schedule]
03-24 18:38:36.922 DEBUG [TSConfig d] ℹ️   Persist config, dirty: [allowIdenticalLocations, debug, desiredAccuracy, distanceFilter, enableHeadless, headlessJobService, logLevel, maxRecordsToPersist, notification, notification.title, notification.text, notification.channelName, startOnBoot, stopOnTerminate]
03-24 18:38:36.928 DEBUG [c g]
ℹ️  LocationAuthorization: Permission granted
03-24 18:38:36.945 INFO [ActivityRecognitionService b]
🎾  Start motion-activity updates
03-24 18:38:36.951 DEBUG [HttpService startMonitoringConnectivityChanges]
🎾  Start monitoring connectivity changes
03-24 18:38:36.951 INFO [TSScheduleManager oneShot]
⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
03-24 18:38:36.958 DEBUG [a c]
🎾  Start monitoring powersave changes
03-24 18:38:36.960 DEBUG [HttpService a]
╔═════════════════════════════════════════════
║ 📶  Connectivity change: connected? true
╠═════════════════════════════════════════════

03-24 18:38:36.975 INFO [HeartbeatService c]
🔴  Stop heartbeat
03-24 18:38:36.978 DEBUG [c h]
ℹ️  LocationAuthorization: Permission granted
03-24 18:38:36.978 INFO [TrackingService a]
🔵  setPace: false → false
03-24 18:38:36.983 DEBUG [TSLocationManagerActivity execute] locationsettings
03-24 18:38:36.984 DEBUG [TSConfig translateDesiredAccuracy] translateDesiredAccuracy (true): -1
03-24 18:38:37.019 DEBUG [TSLocationManagerActivity stop] eventCount: 0
03-24 18:38:37.029 DEBUG [AbstractService a]
🎾  ActivityRecognitionService [eventCount: 1]
03-24 18:38:37.031 DEBUG [ActivityRecognitionService a]
🚘 ️DetectedActivity [type=STILL, confidence=100]
03-24 18:38:37.035 DEBUG [AbstractService a] ⚙️︎  finish ActivityRecognitionService [eventCount: 0, sticky: false]
03-24 18:38:37.073 DEBUG [TSLocationManagerActivity onDestroy]
03-24 18:38:38.041 DEBUG [AbstractService onDestroy]
🔴  ActivityRecognitionService destroyed
03-24 18:38:38.387 DEBUG [AbstractService a]
🎾  LocationRequestService [eventCount: 1]
03-24 18:38:38.389 INFO [LocationRequestService b]
╔═════════════════════════════════════════════
║ motionchange LocationResult: 1
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 49.947748,36.321347 hAcc=13.201 et=+1d0h42m43s372ms alt=188.29998779296875 vAcc=1.9081773 {Bundle[EMPTY_PARCEL]}], age: 53ms, time: 1648139918335

03-24 18:38:38.390 DEBUG [TSLocationManager calculateMedianAccuracy] Median accuracy: 13.201
03-24 18:38:38.390 INFO [TSLocationManager onSingleLocationResult]
🔵  Acquired motionchange position, isMoving: false
03-24 18:38:38.395 DEBUG [AbstractService a] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: false]
03-24 18:38:38.397 DEBUG [AbstractService onDestroy]
🔴  LocationRequestService destroyed
03-24 18:38:38.448 DEBUG [LocationRequestService b] SingleLocationRequest 1 isFinished? true
03-24 18:38:38.448 DEBUG [AbstractService a] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: false]
03-24 18:38:38.448 INFO [ActivityRecognitionService b]
🎾  Start motion-activity updates
03-24 18:38:38.449 DEBUG [TSGeofenceManager startMonitoringStationaryRegion]
🎾  Start monitoring stationary region (radius: 150.0m 49.9477477,36.3213474 hAcc=13.201)
03-24 18:38:38.450 INFO [b persist]
✅  INSERT: aecc71a4-4227-4d24-876f-4ed661b92613
03-24 18:38:38.451 DEBUG [b a]
ℹ️  SHRINK: 1
03-24 18:38:38.459 DEBUG [AbstractService a]
🎾  TrackingService [eventCount: 1]
03-24 18:38:38.460 INFO [TrackingService h]
╔═════════════════════════════════════════════
║ TrackingService motionchange: false
╠═════════════════════════════════════════════

03-24 18:38:38.460 DEBUG [AbstractService a] ⚙️︎  finish TrackingService [eventCount: 0, sticky: true]
03-24 18:38:38.507 DEBUG [AbstractService a]
🎾  ActivityRecognitionService [eventCount: 1]
03-24 18:38:38.509 DEBUG [ActivityRecognitionService a]
🚘 ️DetectedActivity [type=STILL, confidence=100]
03-24 18:38:38.511 DEBUG [AbstractService a] ⚙️︎  finish ActivityRecognitionService [eventCount: 0, sticky: false]
03-24 18:38:39.513 DEBUG [AbstractService onDestroy]
🔴  ActivityRecognitionService destroyed
03-24 18:38:46.971 INFO [ScheduleEvent onOneShot]
╔═════════════════════════════════════════════
║ ⏰ OneShot event fired: TERMINATE_EVENT
╠═════════════════════════════════════════════

03-24 18:38:46.974 DEBUG [TerminateEvent <init>]
ℹ️  TERMINATE_EVENT ignored (MainActivity is still active).
03-24 18:39:07.084 INFO [TSScheduleManager oneShot]
⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
03-24 18:39:22.833 INFO [ScheduleEvent onOneShot]
╔═════════════════════════════════════════════
║ ⏰ OneShot event fired: TERMINATE_EVENT
╠═════════════════════════════════════════════

03-24 18:39:22.841 DEBUG [TerminateEvent <init>]
ℹ️  TERMINATE_EVENT ignored (MainActivity is still active).
03-24 18:45:41.661 INFO [TSScheduleManager oneShot]
⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
03-24 18:45:51.712 INFO [ScheduleEvent onOneShot]
╔═════════════════════════════════════════════
║ ⏰ OneShot event fired: TERMINATE_EVENT
╠═════════════════════════════════════════════

03-24 18:45:51.718 DEBUG [TerminateEvent <init>]
ℹ️  TERMINATE_EVENT ignored (MainActivity is still active).
03-24 18:53:18.460 WARN [RNBackgroundGeolocationModule ready]
⚠️  #ready already called.  Redirecting to #setConfig
03-24 18:53:18.462 DEBUG [TSConfig d] ℹ️   Persist config, dirty: [notification, notification.title]
03-24 18:53:18.469 DEBUG [TSLocationManager clearLastOdometerLocation]
ℹ️  Clear last odometer location
03-24 18:53:18.469 DEBUG [TSGeofenceManager stopMonitoringStationaryRegion]
🔴  Stop monitoring stationary region
03-24 18:53:18.471 INFO [ActivityRecognitionService c]
🔴  Stop motion-activity updates
03-24 18:53:18.472 DEBUG [TSGeofenceManager c] ℹ️  Persist monitored geofences: []
03-24 18:53:18.472 INFO [HeartbeatService c]
🔴  Stop heartbeat
03-24 18:53:18.473 DEBUG [TSGeofenceManager e]
🔴  Stop monitoring geofences
03-24 18:53:18.473 DEBUG [HttpService stopMonitoringConnectivityChanges]
🔴  Stop monitoring connectivity changes
03-24 18:53:18.474 DEBUG [a d]
🔴  Stop monitoring powersave changes
03-24 18:53:18.478 DEBUG [c g]
ℹ️  LocationAuthorization: Permission granted
03-24 18:53:18.485 DEBUG [AbstractService a] ⚙️︎  finish TrackingService [eventCount: 0, sticky: false]
03-24 18:53:18.496 DEBUG [AbstractService a] ⚙️︎  finish GeofencingService [eventCount: 0, sticky: false]
03-24 18:53:18.511 INFO [ActivityRecognitionService b]
🎾  Start motion-activity updates
03-24 18:53:18.517 DEBUG [HttpService startMonitoringConnectivityChanges]
🎾  Start monitoring connectivity changes
03-24 18:53:18.518 DEBUG [AbstractService a] ⚙️︎  finish ActivityRecognitionService [eventCount: 0, sticky: false]
03-24 18:53:18.519 DEBUG [a c]
🎾  Start monitoring powersave changes
03-24 18:53:18.521 DEBUG [HttpService a]
╔═════════════════════════════════════════════
║ 📶  Connectivity change: connected? true
╠═════════════════════════════════════════════

03-24 18:53:18.523 INFO [HeartbeatService c]
🔴  Stop heartbeat
03-24 18:53:18.524 DEBUG [AbstractService onDestroy]
🔴  TrackingService destroyed
03-24 18:53:18.524 DEBUG [c h]
ℹ️  LocationAuthorization: Permission granted
03-24 18:53:18.525 DEBUG [AbstractService onDestroy]
🔴  GeofencingService destroyed
03-24 18:53:18.525 INFO [TrackingService a]
🔵  setPace: false → false
03-24 18:53:18.533 INFO [TSScheduleManager oneShot]
⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
03-24 18:53:18.546 DEBUG [AbstractService onDestroy]
🔴  ActivityRecognitionService destroyed
03-24 18:53:18.558 DEBUG [TSLocationManagerActivity execute] locationsettings
03-24 18:53:18.559 DEBUG [TSConfig translateDesiredAccuracy] translateDesiredAccuracy (true): -1
03-24 18:53:18.600 DEBUG [TSLocationManagerActivity stop] eventCount: 0
03-24 18:53:18.744 DEBUG [TSLocationManagerActivity onDestroy]
03-24 18:53:19.908 DEBUG [AbstractService a]
🎾  LocationRequestService [eventCount: 1]
03-24 18:53:19.909 INFO [LocationRequestService b]
╔═════════════════════════════════════════════
║ motionchange LocationResult: 2
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 49.947752,36.321349 hAcc=12.827 et=+1d0h57m24s883ms alt=188.29998779296875 vAcc=1.919878 {Bundle[EMPTY_PARCEL]}], age: 63ms, time: 1648140799846

03-24 18:53:19.913 DEBUG [AbstractService a] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: false]
03-24 18:53:19.914 DEBUG [AbstractService onDestroy]
🔴  LocationRequestService destroyed
03-24 18:53:19.915 INFO [TSLocationManager onSingleLocationResult]
🔵  Acquired motionchange position, isMoving: false
03-24 18:53:19.915 DEBUG [TSLocationManager calculateMedianAccuracy] Median accuracy: 13.014
03-24 18:53:19.953 INFO [ActivityRecognitionService b]
🎾  Start motion-activity updates
03-24 18:53:19.953 DEBUG [AbstractService a] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: false]
03-24 18:53:19.953 DEBUG [LocationRequestService b] SingleLocationRequest 2 isFinished? true
03-24 18:53:19.954 DEBUG [TSGeofenceManager startMonitoringStationaryRegion]
🎾  Start monitoring stationary region (radius: 150.0m 49.9477521,36.3213487 hAcc=12.827)
03-24 18:53:19.954 INFO [b persist]
✅  INSERT: e8874f4e-0bed-4691-9fc9-92139745bb39
03-24 18:53:19.957 DEBUG [b a]
ℹ️  SHRINK: 1
03-24 18:53:19.962 DEBUG [AbstractService a]
🎾  TrackingService [eventCount: 1]
03-24 18:53:19.962 INFO [TrackingService h]
╔═════════════════════════════════════════════
║ TrackingService motionchange: false
╠═════════════════════════════════════════════

03-24 18:53:19.962 DEBUG [AbstractService a] ⚙️︎  finish TrackingService [eventCount: 0, sticky: true]
03-24 18:53:22.577 INFO [TSScheduleManager oneShot]
⏰ Oneshot TERMINATE_EVENT is already pending
03-24 18:53:22.582 DEBUG [BackgroundGeolocation a]
🔴  Cleared callbacks
03-24 18:53:24.705 DEBUG [TSGeofenceManager$f run]
╔═════════════════════════════════════════════
║ TSGeofenceManager monitoring 0/0
╠═════════════════════════════════════════════
╚═════════════════════════════════════════════
```

</details>

**Comment by shablenko-sednor** [comment] 2022-03-25 08:41
@christocracy it worked...

But why it does not work on short distances?
I tried 
```
disableElasticity: true,
distanceFilter: 1
```
I though that activity recognition should at least detect still\on_foot when I go from one room to another

[background-geolocation.log.gz](https://github.com/transistorsoft/react-native-background-geolocation/files/8348806/background-geolocation.log.gz)

**Comment by christocracy** [comment] 2022-03-25 13:10
It depends on the device and the quality of sensors (accelerometer, gyroscope, magnetometer).

you can shake the device vigorously to simulate walking.  Try it while observing the logs.

**Comment by shablenko-sednor** [comment] 2022-03-25 15:48
That is the problem, I tried different movements, it did not work. Maybe AI is too smart, and can recognize emulation : D (I was on usb debugging, maybe it detects charging and stops recognitions)

**Comment by christocracy** [comment] 2022-03-25 16:18
No.  I do this all the time.

**Comment by abner01061998** [comment] 2022-05-13 13:49
Same Issue with huwaei, location only runs once, then I have to move at least 2km for the background location services start

**Comment by christocracy** [comment] 2022-05-13 13:57
Yes, Huawei are horrible.  There is no software solution that can overcome some particular manufacturer’s additions to the OS that prevent foreground-services from operating as documented.

**Comment by abner01061998** [comment] 2022-05-13 18:11
Not only on Huawei, the same happens in samsung

**Comment by christocracy** [comment] 2022-05-13 18:12
See http://dontkillmyapp.com

**Comment by abner01061998** [comment] 2022-05-13 18:17
its not a problem about closing the app, the main problem is that the motion sensor crash, because the app still open

**Comment by christocracy** [comment] 2022-05-13 18:18
> the motion sensor crash, because the app still open

I have no idea what this means.

**Comment by abner01061998** [comment] 2022-05-13 18:19
The app still open in background but, the location service does not detect any movement

**Comment by christocracy** [comment] 2022-05-13 18:22
Have you applied the settings changes as documented at dontkillmyapp.com?

there’s nothing the plugin can do to overcome restrictions imposed by some particular device manufacturer.

the motion api has an ON/OFF switch, that’s it.   There’s no configuration to it.  It either works, or it doesn’t.  There’s no magic code that can force it to work.

**Comment by abner01061998** [comment] 2022-05-13 18:28
The library does not work even using app on the main screen (opened) the motion api stops unexpectedly and sometimes when you do the start actions it delays for 100 mts EVEN IF YOU GOT THE APP OPEN AND NOT IN BACKGROUND

**Comment by christocracy** [comment] 2022-05-13 18:31
>The library does not work even using app on the main screen (opened)

The plugin's behaviour doesn't change if you have the main screen open, background, or terminated. 

>the motion api stops unexpectedly

What are you talking about?  What makes you think the "motion api stops"?

**Comment by abner01061998** [comment] 2022-05-13 18:41
Steps:

1. Trigger start action
2. The MOTIONCHANGE_FALSE sounds (https://www.transistorsoft.com/docs/background-geolocation-debug-sounds)
3. I drive for 100 meters or more 
4. Then sounds MOTIONCHANGE_TRUE 
5. Then LOCATION_RECORDED keep reproducing and works ok

**Comment by christocracy** [comment] 2022-05-13 18:42
Yes, that all looks normal.  Driving 100m is reasonable.  What is your question?

**Comment by abner01061998** [comment] 2022-05-13 18:44
Is there any way to start inmediatelly ?

**Comment by christocracy** [comment] 2022-05-13 18:44
Yes, by calling `BackgroundGeolocation.changePace(true)`.  See the api docs.

**Comment by christocracy** [comment] 2022-05-13 18:51
`.changePace` is featured prominently in the demo app with a *play / pause* button, like a music player.

<img width="373" alt="Screen Shot 2022-05-13 at 2 49 06 PM" src="https://user-images.githubusercontent.com/14999/168348639-b4648558-0bf7-4db6-b260-083cf1928ba9.png">

**Comment by christocracy** [comment] 2022-05-13 18:56
Right [here](https://github.com/transistorsoft/rn-background-geolocation-demo/blob/master/src/advanced/HomeView.tsx#L209-L213) in the source code.

**Comment by abner01061998** [comment] 2022-05-13 23:02
IT WOOOORKS THANKS :D  I was using pace true before starting the service

**Closed** 2022-05-14 00:50 UTC
